import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const SRC = join(ROOT, ".ai/agents");

const TARGETS = {
  claude: ".claude/agents",
  cursor: ".cursor/agents",
  opencode: ".opencode/agents",
} as const;

type Harness = keyof typeof TARGETS;

type Frontmatter = Record<string, unknown> & {
  targets?: Partial<Record<Harness, Record<string, unknown> | false | null>>;
};

const GENERATED_NOTE =
  "<!-- AUTO-GENERATED by `pnpm sync-agents` from .ai/agents/. Do not edit. -->";

async function syncAgent(file: string): Promise<void> {
  const src = await readFile(join(SRC, file), "utf8");
  const { data, content } = matter(src);
  const { targets = {}, ...base } = data as Frontmatter;

  for (const harness of Object.keys(TARGETS) as Harness[]) {
    const override = targets[harness];
    if (override === false || override === null) continue;

    const merged = { ...base, ...(override ?? {}) };
    const body = `${GENERATED_NOTE}\n\n${content.trimStart()}`;
    const output = matter.stringify(body, merged);
    await writeFile(join(ROOT, TARGETS[harness], file), output);
  }
}

async function main(): Promise<void> {
  const files = (await readdir(SRC)).filter((f) => f.endsWith(".md"));

  for (const harness of Object.keys(TARGETS) as Harness[]) {
    const dir = join(ROOT, TARGETS[harness]);
    await rm(dir, { recursive: true, force: true });
    await mkdir(dir, { recursive: true });
  }

  await Promise.all(files.map(syncAgent));

  console.log(
    `Synced ${files.length} agent(s) to ${Object.keys(TARGETS).length} harness(es)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
