// Portless dev-environment orchestrator.
//
// The frontend runs behind Portless, which gives it a stable, per-worktree
// `https://<worktree>.mal.localhost` URL and eliminates port conflicts when
// several worktrees run at once. The backend stays a plain process on a free
// port, reached only through the frontend's `/api` proxy — keeping a single
// browser origin (no CORS/cookie split) and matching the production shape.
//
// Two resource modes:
//   default      shared Postgres/Redis (the primary checkout's docker stack)
//   --isolated   a standalone per-worktree Postgres/Redis stack, so schema
//                migration work cannot disturb other environments
//
// Invoked via the `dev` / `dev:isolated` package.json scripts.

import { execFile, spawn } from "node:child_process";
import { existsSync, rmSync, writeFileSync } from "node:fs";
import net from "node:net";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const isolated = process.argv.includes("--isolated");
const tearDown = process.argv.includes("--down");

/** Ask the OS for a currently-free TCP port. */
const getFreePort = () =>
  new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.on("error", reject);
    srv.listen(0, "127.0.0.1", () => {
      const { port } = srv.address();
      srv.close(() => resolve(port));
    });
  });

/** Best-effort TCP reachability check, used to warn early in shared mode. */
const probe = (host, port) =>
  new Promise((resolve) => {
    const sock = net.connect({ host, port });
    sock.setTimeout(1000);
    sock.on("connect", () => {
      sock.destroy();
      resolve(true);
    });
    sock.on("error", () => resolve(false));
    sock.on("timeout", () => {
      sock.destroy();
      resolve(false);
    });
  });

const repoRoot = (
  await execFileAsync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  })
).stdout.trim();

// The worktree directory name is what Portless also uses for its subdomain, so
// deriving the isolated stack name from it keeps the two consistent.
const slug = path
  .basename(repoRoot)
  .toLowerCase()
  .replace(/[^a-z0-9-]/g, "-");

const stackName = `mal-${slug}`;

if (tearDown) {
  // Stop and remove this worktree's isolated stack (volumes are bind mounts
  // under .devloop, so the data survives).
  console.log(`[dev-env] tearing down isolated stack "${stackName}"`);
  await execFileAsync("docker", ["compose", "-p", stackName, "down"], {
    cwd: repoRoot,
    encoding: "utf8",
    env: { ...process.env, MAL_STACK: stackName },
  });
  process.exit(0);
}

const serverDir = path.join(repoRoot, "apps", "server");
const frontendDir = path.join(repoRoot, "apps", "frontend");
const portlessEnvFile = path.join(serverDir, ".env.portless.local");

const serverPort = await getFreePort();

if (isolated) {
  const [dbPort, redisPort, adminerPort] = await Promise.all([
    getFreePort(),
    getFreePort(),
    getFreePort(),
  ]);

  console.log(
    `[dev-env] isolated mode — stack "${stackName}" (db:${dbPort} redis:${redisPort} adminer:${adminerPort})`,
  );

  // `--wait` blocks until the Postgres healthcheck passes, so the schema push
  // and the server both start against a ready database.
  await execFileAsync(
    "docker",
    ["compose", "-p", stackName, "up", "-d", "--wait"],
    {
      cwd: repoRoot,
      encoding: "utf8",
      env: {
        ...process.env,
        MAL_STACK: stackName,
        MAL_DB_PORT: String(dbPort),
        MAL_REDIS_PORT: String(redisPort),
        MAL_ADMINER_PORT: String(adminerPort),
      },
    },
  );

  // The server and drizzle-kit both pick this file up last, so it overrides
  // the shared resources in `.env.local`.
  writeFileSync(
    portlessEnvFile,
    `${[
      `# Generated by scripts/dev-env.mjs for isolated worktree stack "${stackName}".`,
      "# Gitignored. Delete it (or run shared `pnpm dev`) to fall back to shared resources.",
      `DATABASE_URL=postgres://my_agent_loop:my_agent_loop@localhost:${dbPort}/my_agent_loop`,
      "REDIS_HOST=localhost",
      `REDIS_PORT=${redisPort}`,
    ].join("\n")}\n`,
  );
  console.log(`[dev-env] wrote ${path.relative(repoRoot, portlessEnvFile)}`);

  // Apply the current schema to the freshly-created database.
  await new Promise((resolve) => {
    spawn("pnpm", ["drizzle", "push"], {
      cwd: repoRoot,
      stdio: "inherit",
    }).on("exit", (code) => {
      if (code !== 0) {
        console.warn(`[dev-env] drizzle push exited ${code}; continuing`);
      }
      resolve();
    });
  });
} else {
  // Shared mode: drop any isolated overrides left behind by a previous run so
  // the server and drizzle-kit fall back to the shared `.env.local` resources.
  if (existsSync(portlessEnvFile)) {
    rmSync(portlessEnvFile);
    console.log("[dev-env] removed stale .env.portless.local");
  }
  const [dbUp, redisUp] = await Promise.all([
    probe("127.0.0.1", 5432),
    probe("127.0.0.1", 6379),
  ]);
  if (!dbUp || !redisUp) {
    console.warn(
      "[dev-env] shared Postgres/Redis not reachable on :5432/:6379 — run `pnpm db:up` in your primary checkout",
    );
  }
  console.log("[dev-env] shared mode — using the shared docker stack");
}

const children = [];
let shuttingDown = false;
const shutdown = (code) => {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const child of children) child.kill("SIGTERM");
  process.exit(code ?? 0);
};
process.on("SIGINT", () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));

// Frontend through Portless. Portless reads apps/frontend/portless.json for the
// name and runs that package's `dev` script, injecting its proxy port.
const frontend = spawn("portless", [], {
  cwd: frontendDir,
  env: { ...process.env, SERVER_URL: `http://localhost:${serverPort}/` },
  stdio: ["inherit", "pipe", "pipe"],
});
children.push(frontend);
frontend.on("exit", (code) => shutdown(code ?? 0));

// Tee Portless output while watching for the assigned URL, which the backend
// needs as APP_BASE_URL (OAuth redirects, `.well-known` metadata).
let frontendUrl;
let resolveUrl;
const urlReady = new Promise((resolve) => {
  resolveUrl = resolve;
});
const makeScanner = (out) => (chunk) => {
  out.write(chunk);
  if (frontendUrl) return;
  const match = String(chunk).match(/https?:\/\/[^\s]*\.localhost\S*/);
  if (match) {
    frontendUrl = match[0].replace(/[)\].,]+$/, "");
    resolveUrl();
  }
};
frontend.stdout.on("data", makeScanner(process.stdout));
frontend.stderr.on("data", makeScanner(process.stderr));

await Promise.race([
  urlReady,
  new Promise((resolve) => setTimeout(resolve, 30_000)),
]);
if (!frontendUrl) {
  frontendUrl = "https://mal.localhost";
  console.warn(
    `[dev-env] could not detect the Portless URL within 30s; assuming ${frontendUrl}`,
  );
}
console.log(
  `[dev-env] frontend ${frontendUrl} — backend on :${serverPort}, reached via the /api proxy`,
);

// Backend as a plain process: it has no browser-facing URL, so it only needs a
// conflict-free port that the frontend's Vite proxy can target.
const server = spawn("pnpm", ["--filter", "@mono/server", "dev"], {
  cwd: repoRoot,
  env: { ...process.env, PORT: String(serverPort), APP_BASE_URL: frontendUrl },
  stdio: "inherit",
});
children.push(server);
server.on("exit", (code) => shutdown(code ?? 0));
